#!/bin/sh

if [ $# -le 0 ]
then
    echo "Usage: $0 <OAK password> [-i <interval>]"
    echo "Calls kinit in fixed intervals, using a user-specified password"
    echo "Options:"
    echo "  -i <interval>: Interval between calls (default: 23h)"
    exit 1
fi

INTER=23h
PWD=$1
shift

while getopts "i:" OPT
do
  case $OPT in
    i) INTER=$OPTARG
      ;;
  esac
done

while true
do
	echo $PWD | kinit $USER
	sleep ${INTER}
done
