#!/bin/sh

if [ $# -le 0 ]
then
    echo "Usage: $0 -i <interval>"
    echo "Calls kinit in fixed intervals, using a user-specified password"
    echo "Options:"
    echo "  -i <interval>: Interval between calls"
    exit 1
fi

echo -n "SUNet ID password: "
read -s PWD
echo

while getopts "i:" OPT
do
  case $OPT in
    i) INTER=$OPTARG
      ;;
  esac
done

while true
do
    echo $PWD | kinit $USER
    if [ $? -eq 0 ]
    then
	echo "Oak kerberos ticket obtained successfully, sleeping for ${INTER} ..." 
    else
	echo "SUNet ID password does not match, exiting" 
	exit 1
    fi
    sleep ${INTER}
done
